### PR TITLE
Do not indent multiline string values

### PR DESCRIPTION
**Pull request by tboyko**
The current version of plist erroneously adds indentation to multiline string values, effectively changing the values. This PR attempts to rectify the issue by inspecting each line of plist/xml (and multiline string value, as a result) and only indents lines that start with an XML character "<".

Tests still pass "bundle exec ruby test/test_parser.rb` though I would appreciate having some additional eyes on this to verify that new issues are not being introduced here.

### Before PR

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>data</key>
	<dict>
		<key>a_multiline_string</key>
		<string>This is a string with 
		multiple line 
		breaks.</string>
		<key>a_normal_string</key>
		<string>This is a string without a line break.</string>
		<key>integer</key>
		<integer>100</integer>
	</dict>
</dict>
</plist>
```

### After PR 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>data</key>
	<dict>
		<key>a_multiline_string</key>
		<string>This is a string with 
multiple line 
breaks.</string>
		<key>a_normal_string</key>
		<string>This is a string without a line break.</string>
		<key>integer</key>
		<integer>100</integer>
	</dict>
</dict>
</plist>
```

### CODE REVIEW

**Comment by tas50** [comment]
Thanks for fixing this @tboyko. This is going to be very handy for us in Chef

**Comment by tboyko** [comment]
In my commit above, I failed to realize that there were multiple test files in the `test/` folder. I ran the additional tests, found that there was a newline bug in the PR, and have fixed it.

Please note that another issue arose that I would appreciate feedback on. Specifically, the `TestDataElements#TestData` method loads a plist, parses it, dumps it, and then checks that the dump is identical to the original plist. This test was initially failing because the original plist file has a `data` object with contents that was indented. When this PR dumps the plist, it does not include the indentation.

The indentation is being removed by the parser process and not the dump process. I tried to find a plist specification document to clarify the treatment of `data` contents and indentation, but could not find any. My assumption is that indentation is irrelevant to the plist specification, and only has meaning when part of a `string` contents.

**Comment by tboyko** [comment]
If `data` contents _should_ indeed be indented, this PR will need to go a more thorough rewrite. Currently, the plist is built in a recursive fashion, starting with descendants and moving upward to the common ancestor (root node), all the while adding indentation to the document. I believe a fix would require something along the lines of a tree traversal so that the indentation level of a given line does not need to be revisited (and an already-processed line doesn't need to be determined to be string related or not).

**Comment by tboyko** [comment]
I made another attempt at this tonight by following the idea in my last comment. Data is now indented as it was previously and I've made an attempt to clean up the code where possible. 

It'd be great if someone else could review this.

**Review by mattbrictson — COMMENTED** [review]
Thanks for PR! Could you add a test that illustrates the bug that is being fixed, sort of like what you explained in the PR description? Maybe like this:

```ruby
  def test_string_containing_newlines
    source = {
      data: {
        a_multiline_string: "This is a string with\nmultiple line\nbreaks.",
        a_normal_string: "This is a string without a line break.",
        integer: 100
      }
    }
    plist_emit_dump = Plist::Emit.dump(source, true)
    assert_equal(<<-EXPECTED, plist_emit_dump.gsub(/\t/, "  "))
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>data</key>
  <dict>
    <key>a_multiline_string</key>
    <string>This is a string with
multiple line
breaks.</string>
    <key>a_normal_string</key>
    <string>This is a string without a line break.</string>
    <key>integer</key>
    <integer>100</integer>
  </dict>
</dict>
</plist>
EXPECTED
  end
```

**Comment by tboyko** [comment]
Thanks @mattbrictson. Added that test.

**Comment by patsplat** [comment]
Thank you @tboyko and @mattbrictson

**Pull request merged**
