### PR TITLE
 Add support for text inside `<![CDATA[ ... ]]>`.

### PR DESCRIPTION
**Pull request by reitermarkus**
Found this in the `com.github.facebook.watchman` LaunchAgent:

```xml
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string><![CDATA[ ... ]]></string>
    </dict>
```

### CODE REVIEW

**Comment by patsplat** [comment]
Nice catch!

Do you mind adding a test case?

**Comment by reitermarkus** [comment]
Done.

**Comment by reitermarkus** [comment]
@patsplat, ping. 😉

**Comment by patsplat** [comment]
build is failing bc Ruby 1.8.7 is old, should we take that out of Travis?

**Comment by mattbrictson** [comment]
I we are going to remove 1.8.7 from the Travis config, then I would suggest officially dropping support for 1.8.7. That would mean adding to the gemspec:

```ruby
spec.required_ruby_version = ">= 1.9.3"
```

**Comment by patsplat** [comment]
Thanks @mattbrictson  

@reitermarkus do you mind updating the spec?

**Comment by patsplat** [comment]
http://www.rubyenterpriseedition.com/
> Notice: Ruby Enterprise Edition has reached End of Life in 2012. The website is still up, and it still works, but it's no longer actively developed and it is no longer supported.

Let's drop `ree` from travis as well?

@reitermarkus thanks for your patience.

**Comment by patsplat** [comment]
@tas50 a version # question - during this PR pulled support for Ruby 1.8.7 and REE.  There is a new line in the gemspec requiring Ruby 1.9.3.

When this releases should it be 3.x.x?  Or is that spec a risk to some chef users, and thus we should bump to 4.x.x?

Thanks in advance for your feedback!

**Comment by tas50** [comment]
We can bump our dep to whatever version make sense for you.

**Comment by patsplat** [comment]
@reitermarkus go ahead and merge thanks again!

**Comment by reitermarkus** [comment]
@patsplat, I would, but I can't. 😉

**Comment by patsplat** [comment]
zoinks sorry was used to my office workflow.

**Pull request merged**
